version: '3.5'

services:
  db:
    image: postgis/postgis:14-3.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Cran8Gat8
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend:
    driver: bridge
